development:
  adapter: postgresql
  database: das6f0gj2ibima
  user: jdnsmsgnpjyvoa
  port: 5432
  password: Qfdg438NEHICtzdysQURnX-GYQ
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: das6f0gj2ibima
  user: jdnsmsgnpjyvoa
  port: 5432
  password: Qfdg438NEHICtzdysQURnX-GYQ
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: das6f0gj2ibima
  user: jdnsmsgnpjyvoa
  port: 5432
  password: Qfdg438NEHICtzdysQURnX-GYQ
  pool: 5
  timeout: 5000