development:
  adapter: postgresql
  host: ec2-54-197-250-40.compute-1.amazonaws.com
  database: d161fnrkch2igv
  user: sacpttghjnpihn
  port: 5432
  password: 9HPdkUuxEYKhVSPEiAZdx9DDA8
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  host: ec2-54-197-250-40.compute-1.amazonaws.com
  database: d161fnrkch2igv
  user: sacpttghjnpihn
  port: 5432
  password: 9HPdkUuxEYKhVSPEiAZdx9DDA8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: ec2-54-197-250-40.compute-1.amazonaws.com
  database: d161fnrkch2igv
  user: sacpttghjnpihn
  port: 5432
  password: 9HPdkUuxEYKhVSPEiAZdx9DDA8
  pool: 5
  timeout: 5000